# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a3706e2a143d576c366e4f003c46fad3209ba2b6e1372e3d2b8e856aabf1cc115394e26b116a765cf7781c226a11fad41a55347de0745b27a2a8bacbb972b549

test:
  secret_key_base: 7abbbed7e7b183a3694eaffcf9f69648cc3761b462900295f0c917a38b3b45326c9ada84b34f4bec09ee0f033149ffc5c742f26e6b4cd80e1b3018c8663d0cbd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
